[package]
name = "big_cheese_server"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gotham = "0.6.0"
mongodb = "2.0.1"
serde = "1.0.130"
tokio = "1.12.0"
